### ISSUE TITLE
这个能支持文字复制粘贴吗😂

### ISSUE THREAD

**Issue by hao-flame** [kuaifan/dootask#2]

**Comment by kuaifan** [comment]
可以的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hao-flame ***@***.***&gt;
发送时间: 2021年12月7日 23:18
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] 这个能支持文字复制粘贴吗�� (Issue #2)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
