### ISSUE TITLE
这个Word 是不是不支持写作。我看好像操作不了

### ISSUE THREAD

**Issue by hao-flame** [kuaifan/dootask#3]
这个问题好像是因为展示版本的问题。本地下载了就可以了。牛啊

**Comment by kuaifan** [comment]
电脑版可以，手机版不行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hao-flame ***@***.***&gt;
发送时间: 2021年12月7日 23:22
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] 这个Word 是不是不支持写作。我看好像操作不了 (Issue #3)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yao0013** [comment]
使用Docker部署遇到如下问题，似乎是数据库连不上
 Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] No route to host (SQL: select * from information_schema.tables where table_schema = dootask and table_name = pre_migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
    699▕         // If an exception occurs when attempting to run a query, we'll format the error
    700▕         // message to include the bindings with SQL, which will make this exception a
    701▕         // lot more helpful to the developer instead of just the database's errors.
    702▕         catch (Exception $e) {
  ➜ 703▕             throw new QueryException(
    704▕                 $query, $this->prepareBindings($bindings), $e
    705▕             );
    706▕         }
    707▕     }

**Comment by yao0013** [comment]
数据库容器报错：

2021-12-08 16:26:48+08:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified

	You need to specify one of MARIADB_ROOT_PASSWORD, MARIADB_ALLOW_EMPTY_ROOT_PASSWORD and MARIADB_RANDOM_ROOT_PASSWORD
