### ISSUE TITLE
docker部署后502问题

### ISSUE THREAD

**Issue by yao0013** [kuaifan/dootask#4]
docker部署后报502，无法进入登录页面

**Comment by kuaifan** [comment]
有时候docker资源不足也会这样，重装试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yao0013 ***@***.***&gt;
发送时间: 2021年12月9日 09:25
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] docker部署后数据库容器有报错 (Issue #4)





 
docker部署后数据库容器有报错，容器无法启动。
 2021-12-08 16:26:48+08:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
 You need to specify one of MARIADB_ROOT_PASSWORD, MARIADB_ALLOW_EMPTY_ROOT_PASSWORD and MARIADB_RANDOM_ROOT_PASSWORD  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yao0013** [comment]
你好，问题依然存在，是否php路由这一块有点问题

**Comment by kuaifan** [comment]
私聊一下，aipaw@qq.com
