### ISSUE TITLE
这是我会用GITHUB以来第一次给出的STAR

### ISSUE THREAD

**Issue by pistacio520** [kuaifan/dootask#5]
这是我会用GITHUB以来第一次给出的STAR.
希望它可以走的更远。

**Comment by kuaifan** [comment]
谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ChenQinPing ***@***.***&gt;
发送时间: 2021年12月9日 14:03
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] 这是我会用GITHUB以来第一次给出的STAR (Issue #5)





 
这是我会用GITHUB以来第一次给出的STAR.
 希望它可以走的更远。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
