### ISSUE TITLE
nginx 502

### ISSUE THREAD

**Issue by ae86sen** [kuaifan/dootask#6]
装好之后报nginx502是咋回事啊？

**Comment by kuaifan** [comment]
重装最新版试试



发自我的iPhone


------------------ Original ------------------
From: Acient One ***@***.***&gt;
Date: Thu,Dec 9,2021 7:09 PM
To: kuaifan/dootask ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [kuaifan/dootask] nginx 502 (Issue #6)





 
装好之后报nginx502是咋回事啊？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ae86sen** [comment]
hi，安装新版的最后还是nginx502，是不是跟安装的时候有这么一段报错有关系呢？能麻烦帮看一下吗，thanks！


| |
listeningsss
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/9/2021 ***@***.***> wrote：

重装最新版试试



发自我的iPhone


------------------ Original ------------------
From: Acient One ***@***.***&gt;
Date: Thu,Dec 9,2021 7:09 PM
To: kuaifan/dootask ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [kuaifan/dootask] nginx 502 (Issue #6)






装好之后报nginx502是咋回事啊？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kuaifan** [comment]
aipaw@live.cn

**Comment by lvchaoin** [comment]
同问，怎么装都是502
